validations:
  - name: default
    enforcement: Error
  # example of configuring enum validation to allow addition of new enum constraint values
  - name: enum
    enforcement: Error
    configuration:
      additionPolicy: Allow
